{% set name = "findimports" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9826a0cbbd98c91894197ebb3490f15c180397d27c37aa36b157afa986a7bc0f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - findimports
  commands:
    - findimports -h

about:
  home: https://github.com/mgedmin/findimports
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python module import analysis tool

  # The remaining entries in this section are optional, but recommended.
  description: |
    FindImports extracts Python module dependencies by parsing source files. It
    can report names that are imported but not used, and it can generate module
    import graphs in ASCII or graphviz formats.
  dev_url: https://github.com/mgedmin/findimports

extra:
  recipe-maintainers:
    - moorepants
