{% set name = "findimports" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4532cb9714e7772854f941b1cdb09cb5d377838b0f6f926940097778bcf818e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - findimports
  commands:
    - findimports -h

about:
  home: https://github.com/mgedmin/findimports
  license: MIT
  license_file: LICENSE
  summary: Python module import analysis tool

  # The remaining entries in this section are optional, but recommended.
  description: |
    FindImports extracts Python module dependencies by parsing source files. It
    can report names that are imported but not used, and it can generate module
    import graphs in ASCII or graphviz formats.
  dev_url: https://github.com/mgedmin/findimports

extra:
  recipe-maintainers:
    - moorepants
